#!/usr/bin/env node
import { readFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const repoRoot = resolve(root, "..");
const source = await readFile(resolve(root, "src/main.js"), "utf8");
const userscript = await readFile(resolve(repoRoot, "chatgpt-codex.user.js"), "utf8");
const content = await readFile(resolve(root, "extension/content.js"), "utf8");
const manifest = JSON.parse(await readFile(resolve(root, "extension/manifest.json"), "utf8"));
const fail = (m) => { console.error("self-check failed:", m); process.exitCode = 1; };
if (!userscript.includes("@match        https://chatgpt.com/*")) fail("userscript @match missing");
if (!userscript.includes("cgpt-codex-hotzone")) fail("top hot zone missing");
if (!userscript.includes("data-window=\"minimize\"")) fail("window controls missing");
if (!source.includes('type: "bookmarks"')) fail("bookmark bridge missing");
if (content.trim() !== source.trim()) fail("extension content is not generated from src/main.js");
if (!manifest.permissions.includes("bookmarks")) fail("bookmarks permission missing");
if (!manifest.permissions.includes("windows")) fail("windows permission missing");
if (!manifest.host_permissions.includes("https://chatgpt.com/*")) fail("chatgpt host permission missing");
if (/fetch\s*\(/.test(source)) fail("skin source must not intercept or call ChatGPT network APIs");
if (!process.exitCode) console.log("self-check passed");
